pulibrary/pulbot

apps.json

Add pulmap

---

apps.json

Add production environment to pulmap

---

apps.json

We can merge this once https://github.com/pulibrary/pul_solr/pull/195 is merged.

Add solr8-staging as a deploy target for pul_solr

---

apps.json

Adds alma_qa for orangelight

---

scripts/listener_middleware.coffee

Add Kate, remove Nikitas

---

apps.json

Adds qa env for orangelight closes #38

---

scripts/listener_middleware.coffee

Add Hector

---

scripts/listener_middleware.coffee

Ensuring that @bess has the proper privileges to deploy pulbot

---

apps.json

go ahead and remove pomegranate target

Deploy dpul to new repo location

---

scripts/listener_middleware.coffee

Removed Kevin M.'s Slack ID

---

config/deploy.rb
config/deploy/production.rb
package-lock.json

Companion to https://github.com/pulibrary/princeton_ansible/pull/2373

Deploy to appdeploy1.

---

apps.json

Remove bibdata alma-staging and alma-production environments

---

apps.json

Refs https://github.com/pulibrary/orangelight/issues/2621

Remove orangelight alma targets.

---

apps.json

Resolves https://github.com/pulibrary/oawaiver/issues/32

Adding entries for the oawaiver staging and production environments

---

apps.json

Until we have new staging infra
refs pulibrary/orangelight#2621

Remove orangelight staging target

---

scripts/listener_middleware.coffee

Add Xander

---

apps.json

Add staging in orangelight

---

apps.json

This resolves https://github.com/pulibrary/ouranos/issues/20

Adds support for deploying pulibrary/ouranos into the staging environment

---

scripts/listener_middleware.coffee

adds Alicia to pulbot admins

---

.gitignore
apps.json

Work toward https://github.com/pulibrary/pdc_describe/issues/4

Add PDC Describe to pulbot deploy

---

apps.json

deploy solr to staging and production

---

scripts/listener_middleware.coffee

Removed Chuck

---

apps.json

Adding tigerdata for the deploying into the staging and production environments
